### ISSUE TITLE
unexpected keyword argument 'special_level'

### ISSUE THREAD

**Issue by ElGringoNG** [OBone-git/Cozytouch-domoticz#17]
Au changement d'une température d'une zone de ma pompe à chaleur dans l'onglet MESURES de domoticz version 4.10717, j'ai le message suivant :
`pi@domoticz:~/domoticz/scripts/python $ sudo python /home/pi/domoticz/scripts/python/cozytouch_V37.py
¤¤¤¤ Demarrage script cozytouch <=> domoticz version 4 (debug :1)
Version python : 2.7.13
**** Test existence / creation configuration cozytouch (hardware domoticz + fichier de sauvegarde) ****
Fichier de sauvegarde de la configuration : /home/pi/domoticz/scripts/python/cozytouch_save
idx hardware cozytouch dans le fichier de sauvegarde de la configuration : 8
GET->   http://192.168.x.xx:8080/json.htm?type=hardware   :   200
idx hardware cozytouch dans domoticz : 8
**** Fin fonction test ****
Test présence du fichier de sauvegarde cozytouch et virtual hardware domoticz OK

**** Tentative interrogation serveur Cozytouch sans login, avec cookie login précédent ****
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/refreshAllStates   :   401
Erreur HTTP 401 :
!!!! Echec interrogation serveur Cozytouch sans login, connexion serveur Cozytouch ****
 POST-> https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/login | userId=****&userPassword=**** : 200
Authentification serveur cozytouch OK
Connexion serveur Cozytouch reussie
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/refreshAllStates   :   200
Requete refreshAllStates reussie
**** Decouverte devices ****
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/getSetup   :   200

Gateway Cozytouch : etat on / connexion : OK / version : 2019.5.4

**** Demarrage mise a jour devices ****
Mise a jour device 0 : io:AtlanticPassAPCZoneControlMainComponent
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/python/cozytouch_V37.py", line 1576, in <module>
    decouverte_devices()
  File "/home/pi/domoticz/scripts/python/cozytouch_V37.py", line 663, in decouverte_devices
    maj_device(data,name,p,x) # mise à jour du device
  File "/home/pi/domoticz/scripts/python/cozytouch_V37.py", line 1357, in maj_device
    special_level = 'auto',special_setting='setHeatingCoolingAutoSwitch',special_setting_parameter_on='on',special_setting_parameter_off='off')
TypeError: gestion_switch_selector_domoticz() got an unexpected keyword argument 'special_level'`

**Comment by OBone-git** [comment]
Hello @ElGringoNG as tu toujours ce problème après mise à jour du script ?

**Comment by ElGringoNG** [comment]
Je n'ai pas retenté pour le moment.

**Comment by ElGringoNG** [comment]
Bonjour,
J'ai remis à jour et refait un essai, j'ai ensuite donné une consigne de changement de temperature via domoticz puis relancer le script : 

pi@domoticz:~/domoticz/scripts/python $ sudo python /home/pi/domoticz/scripts/python/cozytouch.py
¤¤¤¤ Demarrage script cozytouch <=> domoticz version 4 (debug :1)
Version python : 2.7.13
**** Test existence / creation configuration cozytouch (hardware domoticz + fichier de sauvegarde) ****
Fichier de sauvegarde de la configuration : /home/pi/domoticz/scripts/python/cozytouch_save
idx hardware cozytouch dans le fichier de sauvegarde de la configuration : 8
GET->   http://192.168.1.15:8080/json.htm?type=hardware   :   200
idx hardware cozytouch dans domoticz : 8
**** Fin fonction test ****
Test présence du fichier de sauvegarde cozytouch et virtual hardware domoticz OK

**** Tentative interrogation serveur Cozytouch sans login, avec cookie login précédent ****
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/refreshAllStates   :   200
Requete de test sans login reussie, bypass login

**** Decouverte devices ****
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/getSetup   :   200

Gateway Cozytouch : etat on / connexion : OK / version : 2019.5.4

**** Demarrage mise a jour devices ****
Mise a jour device 0 : io:AtlanticPassAPCZoneControlMainComponent
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/python/cozytouch.py", line 1580, in <module>
    decouverte_devices()
  File "/home/pi/domoticz/scripts/python/cozytouch.py", line 665, in decouverte_devices
    maj_device(data,name,p,x) # mise à jour du device
  File "/home/pi/domoticz/scripts/python/cozytouch.py", line 1361, in maj_device
    special_level = 'auto',special_setting='setHeatingCoolingAutoSwitch',special_setting_parameter_on='on',special_setting_parameter_off='off')
TypeError: gestion_switch_selector_domoticz() got an unexpected keyword argument 'special_level'
pi@domoticz:~/domoticz/scripts/python $
